spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&useSSL=false
  session:
    store-type: none
server:
   session:
     timeout: 600
   port: 8060
security:
  basic:
    enabled: false